#!/usr/bin/env bash
set -euo pipefail

ENVS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_ORDER=(go node python rust)
enabled_raw=${1:-}
DEV_ENV_HOME=${DEV_ENV_HOME:-/opt/dev-env}
SOURCE_PROFILE=${SOURCE_PROFILE:-}

fail() {
    echo "❌ $*" >&2
    exit 1
}

is_valid_toolchain() {
    case "$1" in
        go|node|python|rust) return 0 ;;
        *) return 1 ;;
    esac
}

contains_word() {
    case " $1 " in
        *" $2 "*) return 0 ;;
        *) return 1 ;;
    esac
}

normalize_enabled_envs() {
    local raw selected token tool ordered env
    raw=${1//,/ }
    selected=""

    [ -n "${raw// /}" ] || fail "ENABLED_ENVS is required"

    for token in $raw; do
        tool=${token%%@*}
        if [ "$token" = "all" ]; then
            selected="${TOOLCHAIN_ORDER[*]}"
            continue
        fi
        is_valid_toolchain "$tool" || fail "Unknown toolchain '$tool'. Available: go,node,python,rust,all"
        contains_word "$selected" "$tool" || selected="${selected:+$selected }$tool"
    done

    ordered=""
    for env in "${TOOLCHAIN_ORDER[@]}"; do
        if contains_word "$selected" "$env"; then
            ordered="${ordered:+$ordered }$env"
        fi
    done

    [ -n "$ordered" ] || fail "No valid toolchain selected"
    printf '%s\n' "$ordered"
}

enabled_envs="$(normalize_enabled_envs "$enabled_raw")"
profile_file=/etc/profile.d/dev-tools.sh

apply_source_profile() {
    local pair key value
    [ -n "$SOURCE_PROFILE" ] || return 0
    IFS=';' read -r -a source_pairs <<< "$SOURCE_PROFILE"
    for pair in "${source_pairs[@]}"; do
        [ -n "$pair" ] || continue
        key=${pair%%=*}
        value=${pair#*=}
        export "$key=$value"
    done
}

apply_source_profile

cat > "$profile_file" <<'PROFILE'
# Generated by dev-container. Do not edit inside the container.
dev_path_prepend() {
    [ -n "${1:-}" ] || return 0
    case ":$PATH:" in
        *":$1:"*) ;;
        *) PATH="$1:$PATH" ;;
    esac
}
PROFILE

mkdir -p /opt/dev-container
printf '%s\n' "${enabled_envs// /,}" > /opt/dev-container/enabled-envs
mkdir -p "$DEV_ENV_HOME"

for env in $enabled_envs; do
    module_dir="$ENVS_ROOT/$env"
    [ -d "$module_dir" ] || fail "Toolchain module '$env' is missing"
    [ -f "$module_dir/install.sh" ] || fail "Toolchain module '$env' is missing install.sh"

    echo "➡️  Installing $env toolchain..."
    bash "$module_dir/install.sh"

    if [ -f "$module_dir/profile.sh" ]; then
        {
            printf '\n# %s\n' "$env"
            cat "$module_dir/profile.sh"
        } >> "$profile_file"
    fi
done

cat >> "$profile_file" <<'PROFILE'

export PATH
PROFILE

chmod 0644 "$profile_file"
